### ISSUE TITLE
Fix search methods

### ISSUE THREAD

**Issue by kazhamiakin** [smartcommunitylab/idea-management#1]
Currently, the search methods do not cover all the combinations (e.g., search by call does not consider tags). Also, it is necessary to check first whether we search by call, otherwise by category. It is better to define two methods:
- searchByCallAndCategoryAndTags (order by creation)
- searchPopularByCallAndCategoryAndTags

all the checks should be done inside

**Comment by mirkoperillo** [comment]
done
