### ISSUE TITLE
scorrimento portlet verso il basso

### ISSUE THREAD

**Issue by micnori** [smartcommunitylab/idea-management#9]
"se tento di cliccar sulle frecce degli eventi in alto a destra non me lo permette perche fa scorrer verso il basso la tendina del menu piattaforma e questo avviene gia prima di arrivarci sopra (procedo salendo dal basso in alto e non viceversa)"

Sistemato: verificare se su qualche pagina lo fa ancora

**Comment by oskarnrk** [comment]
Ho fatto un giro di controllo mettendo le Nested Portlet dove servivano, se ne saltano fuori ancora sappiamo come correggere. Intanto chiudo.
